version: 2
updates:
  # --- GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # --- SDK
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  